version: '3'

services:
  api-solid-pg:
    image: bitnami/postgresql
    environment:
      POSTGRES_USERNAME: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DATABASE: apisolid
    ports:
      - "5432:5432"
   